### ISSUE TITLE
Printing Common Files not working for PDF - on some MacOS Mojave 10.14.1 (and 10.14.6)

### ISSUE THREAD

**Issue by d3-vitalii-baziuk** [neodynamic/JSPrintManager#5] opened 2019-07-03 14:58 UTC
Hi,

I've used the samples from here: https://www.neodynamic.com/Products/Help/JSPrintManager2.0/articles/jsprintmanager.html

And the printing of PNG is working properly with `JSPM.PrintFile()` call but PDF and TXT are not working with all of these methods:
- `JSPM.PrintFilePDF()`
- `JSPM.PrintFileTXT()`
- `JSPM.PrintFile()`

Even more: `.PrintFileTXT()` expects only 3 params, not 4 which causes some exception. And printing with 3 params emits printing an only passed string, not file loaded by URL (actually that string).

You can test it with your docs example:
```
<script type="text/javascript">

    JSPM.JSPrintManager.auto_reconnect = true;
    JSPM.JSPrintManager.start();
    JSPM.JSPrintManager.WS.onStatusChanged = function () {
        if (JSPM.JSPrintManager.websocket_status == JSPM.WSStatus.Open) {
            var cpj = new JSPM.ClientPrintJob();
            cpj.clientPrinter = new JSPM.DefaultPrinter();
            var my_file1 = new JSPM.PrintFilePDF('/files/LoremIpsum.pdf', JSPM.FileSourceType.URL, 'MyFile.pdf', 1);
            var my_file2 = new JSPM.PrintFileTXT('/files/LoremIpsum.txt', JSPM.FileSourceType.URL, 'MyFile.txt', 1);
            cpj.files.push(my_file1);
            cpj.files.push(my_file2);
            cpj.sendToClient();
        }
    };

</script>

```

The same result with cloned repo https://jsprintmanager.azurewebsites.net/ and trying this page, working ONLY for IMAGES:
![image](https://user-images.githubusercontent.com/49312836/60603229-07b28d80-9dbe-11e9-9dfa-8cf5935d12c7.png)

Thanks in advance

**Comment by neodynamic** [comment] 2019-07-03 16:01
In the online demo https://jsprintmanager.azurewebsites.net under "Print Images & Docs", the code uses PrintFile class. When using that class and a PDF file, the printing will rely on the default pdf software installed at the client machine (Adobe Reader or Foxit in Windows) and in Windows 10, MS Edge browser is the default one which will not print at all. To avoid that, you should try the PrintFilePDF class which is used in the same demo website but under "Advanced PDF printing". There you can specify a URL to a pdf file like this "https://neodynamic.com/temp/loremipsum.pdf" and it should work

**Comment by d3-vitalii-baziuk** [comment] 2019-07-03 16:20
Thanks, @neodynamic

But there are two things:

1. I've tried to call .PrintFilePDF() method without Advanced options (like tray, paper etc.) and it was just nothing happen.
2. There is additional not related to PDF issue Advanced mode. That example requires Tray selection, but printer info contains empty  Tray list, so I'm getting "Invalid tray name". But if I don't need any advanced options I should have the way to get it done just using .PrintFilePDF() method instead .PrintFile().


So is there the ways to print TXT and PDF files without any advanced options.

Official website and docs says that ```PDF, TXT, DOC/x, XLS/x, JPG, PNG, and more! PDF, TXT, PNG, JPG and BMP are natively supported; others will require external software like Word, Excel, LibreOffice, etc.```

**Comment by neodynamic** [comment] 2019-07-03 16:53
You can print PDF without advanced options by using PrintFilePDF. Try this code and be sure that the /files/LoremIpsum.pdf exists in your website project OR use the URL https://neodynamic.com/temp/loremipsum.pdf

`<script type="text/javascript">

    JSPM.JSPrintManager.auto_reconnect = true;
    JSPM.JSPrintManager.start();
    JSPM.JSPrintManager.WS.onStatusChanged = function () {
        if (JSPM.JSPrintManager.websocket_status == JSPM.WSStatus.Open) {
            var cpj = new JSPM.ClientPrintJob();
            cpj.clientPrinter = new JSPM.DefaultPrinter();
            var my_file1 = new JSPM.PrintFilePDF('/files/LoremIpsum.pdf', JSPM.FileSourceType.URL, 'MyFile.pdf', 1);
            cpj.files.push(my_file1);
            cpj.sendToClient();
        }
    };

    </script>`

You're right that PrintFileTXT is not correctly described in the help. The PrintFileTXT requires the string/text content of the file not the URL. Here's a sample code

`<script type="text/javascript">

    JSPM.JSPrintManager.auto_reconnect = true;
    JSPM.JSPrintManager.start();
    JSPM.JSPrintManager.WS.onStatusChanged = function () {
        if (JSPM.JSPrintManager.websocket_status == JSPM.WSStatus.Open) {
            var cpj = new JSPM.ClientPrintJob();
            cpj.clientPrinter = new JSPM.DefaultPrinter();
            var my_file1 = new JSPM.PrintFileTXT('Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dapibus purus vitae purus sollicitudin, nec semper tortor sodales. Sed sed urna quis tortor tempus congue nec a enim. Nunc non lectus lectus. Nam id lectus nec elit tempor congue. Donec placerat sapien ut enim blandit fermentum. Phasellus vitae efficitur purus. Morbi vitae laoreet ex, maximus cursus nulla. Donec varius mauris id facilisis scelerisque. Etiam at facilisis diam, et sagittis augue.', 'MyFile.txt', 1);
            cpj.files.push(my_file1);
            cpj.sendToClient();
        }
    };

    </script>`

**Comment by d3-vitalii-baziuk** [comment] 2019-07-03 17:07
Thanks, yeah that's I have been tried.
Txt works in that way.
But PDF does nothing :(
Have you tested PDF printing in this way?

**Comment by neodynamic** [comment] 2019-07-03 17:08
Yes, we tested the pdf and it's working. Which OS are you using?

**Comment by d3-vitalii-baziuk** [comment] 2019-07-03 17:22
MacOS 10.14.1
Chrome 75.0.3770.100 (Official Build) (64-bit)

**Comment by neodynamic** [comment] 2019-07-03 17:52
Which printer brand and model are you specifying?

**Comment by d3-vitalii-baziuk** [comment] 2019-07-03 17:54
*Brother DCP-7057W*

But just would like to remind you, that images and txt from string are working.

**Comment by neodynamic** [comment] 2019-07-03 18:03
It seems that there's a problem with Brother driver on Mac when printing pdf. Do you have another printer there for making a simple test and to verify that?

**Comment by d3-vitalii-baziuk** [comment] 2019-07-03 18:08
I think I will have a chance to try another printer tomorrow.
Thank you very much for your time.

I'll provide another printer testing result tomorrow.

**Comment by d3-vitalii-baziuk** [comment] 2019-07-04 14:15
Hey @neodynamic

Tested on printer `Samsung SCX-4300 Series` and it has the same result.

There is one bad difference - a Zoomed In content on paper (only part of an image is printed on paper (not fit), and TXT has a bigger size on paper and doesn't fix (some text is cut at the end of paper)).

But the main issue is still existing - **PDF printing does not anything.**

Here is my code which is based on your codes too:

- WORKING one - *print image file to image*

```
                    var cpj = new JSPM.ClientPrintJob();
                    cpj.clientPrinter = new JSPM.DefaultPrinter();
                    var my_file = new JSPM.PrintFile('download.png', JSPM.FileSourceType.URL, 'file.png', 1);
                    cpj.files.push(my_file);
                    cpj.sendToClient();
```

- WORKING one - *print string data to TXT*

```
                    var cpj = new JSPM.ClientPrintJob();
                    cpj.clientPrinter = new JSPM.DefaultPrinter();
                    var my_file = new JSPM.PrintFileTXT('Some text', 'file.txt', 1);
                    cpj.files.push(my_file);
                    cpj.sendToClient();
```

- NOT WORKING one - *print PDF file to PDF*

```
                    var cpj = new JSPM.ClientPrintJob();
                    cpj.clientPrinter = new JSPM.DefaultPrinter();
                    var my_file = new JSPM.PrintFilePDF('/files/LoremIpsum.pdf', JSPM.FileSourceType.URL, 'MyFile.pdf', 1);
                    cpj.files.push(my_file);
                    cpj.sendToClient();
```

- And as you mentioned yesterday - there is NO way to *print TXT file to TXT*.


:(

**Comment by neodynamic** [comment] 2019-07-04 14:21
1. About PDF printing... which kind of user account are you running? Has it admin permissions? 

2. You can print txt file but you have to read the content of such file by using XHR so then you can pass the text to the PrintFileTXT class.

**Comment by d3-vitalii-baziuk** [comment] 2019-07-04 14:38
1. Do you mean OS user or user of what?

2. Ok, will take a look at it later, PDF is the highest priority for now. Thanks

**Comment by neodynamic** [comment] 2019-07-04 14:50
Yes, the OS user account in the client machine (macOS in this case)

**Comment by d3-vitalii-baziuk** [comment] 2019-07-04 14:52
Yes, admin.

**Comment by neodynamic** [comment] 2019-07-04 15:14
Have you tried another pdf file? If not, please try open an image or doc with Preview app on macOS, then select File > Export as PDF... give it a name and then use it. We want to determine whether the sample pdf is not working in your system

**Comment by d3-vitalii-baziuk** [comment] 2019-07-04 15:52
Yes tried other ones, and just now tried Exported ones as you said, both from .png and from .docs files using Preview macOS app.

Weird :(

Let me know please have you had a chance to try PDF printing on macOS?
I have another macOS computer but not sure it makes sense try it.

**Comment by neodynamic** [comment] 2019-07-04 16:38
We tried here with macOS High Sierra (10.13) and works just fine. If you can try with another machine that'll be great to know.

**Comment by d3-vitalii-baziuk** [comment] 2019-07-09 13:23
@neodynamic I have not had a chance to check it on other macOS but it works on Windows 10.
So seems macOS specific issue (maybe only some versions) :(

**Comment by d3-vitalii-baziuk** [comment] 2019-07-24 10:29
Hey @neodynamic I've got back to working on PDF printing and can confirm that PDF printing:
1. Works for **Windows 10**
2. Works for **macOS Sierra 10.12.6**
3. Doesn't work for **macOS Sierra 10.14.1**

**Comment by neodynamic** [comment] 2019-07-24 11:12
Thanks for the feedback @d3-vitalii-baziuk 
We're investigating it and let you know asap.

**Comment by neodynamic** [comment] 2019-07-25 13:28
@d3-vitalii-baziuk We installed Mojave (10.14.4) and two printers, a virtual PDF printer called [PDFWriter](https://sourceforge.net/projects/pdfwriterformac/) and a physical HP Photosmart C4780
Using our online demo we could print a PDF file to both printers without any issues.
May you tell us which version of Python is installed in your Mojave box?

**Comment by d3-vitalii-baziuk** [comment] 2019-07-25 13:31
@neodynamic I believe it's 2.7.10.
![image](https://user-images.githubusercontent.com/49312836/61878402-99af4100-aef9-11e9-83f9-5ba7c5f9164e.png)

**Comment by neodynamic** [comment] 2019-07-25 13:48
Same version here so weird we can print without issues here. We're running macOS 10.14.4 while your is 10.14.1 so may you update it?

**Comment by d3-vitalii-baziuk** [comment] 2019-07-25 13:50
Will do that tomorrow or on the weekend and let you know after, thanks!

**Comment by d3-vitalii-baziuk** [comment] 2019-09-04 11:18
Still doesn't work on the same Mac, the version is updated to **10.14.4** 
Don't have an idea why it's happening, but works on other machines.
Anyway, thanks.

**Comment by neodynamic** [comment] 2019-09-04 11:38
We cannot reproduce the issue in that same OSX version. FYI, in v3 we'll ship a brand new pdf printing option so we expect it to work flawlessly.

**Comment by mattchatterley** [comment] 2019-12-03 12:43
We are also experiencing this on OSX 10.14.6 - the same example works perfectly on a Windows machine.

**Comment by neodynamic** [comment] 2019-12-03 15:16
Thanks @mattchatterley por the feedback. Sadly, the issue is not always reproducible. V3 will ship a new pdf printing support that we expect it to work flawlessly. V3 ETA is Jan/Feb

**Comment by neodynamic** [comment] 2020-07-02 20:47
V3 is finally supporting custom pdf printing on macOS so this issue should be fixed.

**Closed by neodynamic** 2020-07-02 20:47 UTC
